// Bilingual UI strings for the randomization tool.
export type Lang = "en" | "tr";

type Dict = Record<string, { en: string; tr: string }>;

const D: Dict = {
  eyebrow: {
    en: "Randomization for bioequivalence & crossover trials",
    tr: "Biyoeşdeğerlik & çapraz çalışmalar için randomizasyon",
  },
  heading: { en: "Randomization.", tr: "Randomizasyon." },
  lede: {
    en: "Generate verifiable, reproducible randomization schedules for bioequivalence, bioavailability, and crossover trials — including replicate designs for highly variable drugs. Every schedule carries a seed, algorithm version, and SHA-256 verification code so an independent auditor can reproduce it. Runs entirely in your browser; your data never leaves this device.",
    tr: "Biyoeşdeğerlik, biyoyararlanım ve çapraz çalışmalar için — yüksek değişkenlikli ilaçlara yönelik replicate tasarımlar dâhil — doğrulanabilir, yeniden üretilebilir randomizasyon listeleri üretin. Her liste; seed, algoritma sürümü ve SHA-256 doğrulama kodu taşır; böylece bağımsız bir denetçi listeyi yeniden üretebilir. Tamamen tarayıcınızda çalışır; veriniz bu cihazdan çıkmaz.",
  },
  studyParams: { en: "Study parameters", tr: "Çalışma parametreleri" },
  configure: { en: "configure", tr: "yapılandır" },
  method: { en: "Method", tr: "Yöntem" },
  parallel: { en: "Parallel", tr: "Paralel" },
  crossover: { en: "Crossover", tr: "Çapraz" },
  design: { en: "Crossover design", tr: "Çapraz tasarım" },
  selectDesign: { en: "Select a design", tr: "Bir tasarım seçin" },
  totalVolunteers: { en: "Total volunteers", tr: "Toplam gönüllü" },
  drugs: { en: "Drugs", tr: "İlaçlar" },
  drugsHintReplicate: {
    en: "First = Test (T), second = Reference (R).",
    tr: "İlki = Test (T), ikincisi = Referans (R).",
  },
  periodsDerived: { en: "Periods", tr: "Dönem" },
  seqCount: { en: "Sequences", tr: "Sekans" },
  seed: { en: "Seed", tr: "Seed" },
  randomize: { en: "randomize", tr: "rastgele" },
  blockSize: { en: "Block size", tr: "Blok boyutu" },
  pleaseSelect: { en: "Please select", tr: "Lütfen seçin" },
  allocationRatio: { en: "Allocation ratio", tr: "Tahsis oranı" },
  studyCode: { en: "Study / protocol code (optional)", tr: "Çalışma / protokol kodu (opsiyonel)" },
  generate: { en: "Generate", tr: "Üret" },
  exportPdf: { en: "Export PDF", tr: "PDF indir" },
  selectMethodFirst: { en: "Generate a schedule first.", tr: "Önce bir liste üretin." },
  suggestionPrefix: { en: "Try", tr: "Deneyin:" },
  applySuggested: { en: "Apply suggested size", tr: "Önerilen boyutu uygula" },
  // result + audit
  idCol: { en: "ID", tr: "ID" },
  seqCol: { en: "Sequence", tr: "Sekans" },
  period: { en: "Period", tr: "Dönem" },
  treatment: { en: "Treatment", tr: "Tedavi" },
  auditTitle: { en: "Audit & reproducibility", tr: "Denetim & yeniden üretim" },
  verified: { en: "verifiable", tr: "doğrulanabilir" },
  mDesign: { en: "Design", tr: "Tasarım" },
  mTreatments: { en: "Treatments", tr: "Tedavi sayısı" },
  mSequences: { en: "Sequences", tr: "Sekans sayısı" },
  mPerSeq: { en: "Subjects / sequence", tr: "Denek / sekans" },
  mSeed: { en: "Seed", tr: "Seed" },
  mAlgo: { en: "Algorithm", tr: "Algoritma" },
  mBlock: { en: "Block size", tr: "Blok boyutu" },
  mGenerated: { en: "Generated", tr: "Üretim zamanı" },
  mTool: { en: "Tool", tr: "Araç" },
  mVerification: { en: "Verification code", tr: "Doğrulama kodu" },
  varianceBalanced: { en: "variance-balanced", tr: "varyans-dengeli" },
  reproCheck: { en: "Reproducibility check", tr: "Yeniden üretim kontrolü" },
  reproOk: { en: "Reproduced — identical (hash match)", tr: "Yeniden üretildi — birebir aynı (hash eşleşti)" },
  reproMismatch: { en: "Mismatch — hash differs", tr: "Uyuşmuyor — hash farklı" },
  reproHint: {
    en: "Re-runs the same seed + parameters and compares the SHA-256 hash.",
    tr: "Aynı seed + parametrelerle yeniden üretip SHA-256 hash'i karşılaştırır.",
  },
  // Faz 2 — field workflow
  reserveSubjects: { en: "Reserve subjects", tr: "Yedek denekler" },
  reserveTag: { en: "Reserve", tr: "Yedek" },
  optionsTitle: { en: "Numbering & reserves", tr: "Numaralandırma & yedekler" },
  options: { en: "options", tr: "seçenekler" },
  randPrefix: { en: "Rand. no prefix", tr: "Rand. no öneki" },
  startNo: { en: "Start", tr: "Başlangıç" },
  padWidth: { en: "Digits", tr: "Basamak" },
  enrollEnabled: { en: "Separate enrollment number", tr: "Ayrı kayıt numarası" },
  enrollPrefix: { en: "Enroll. prefix", tr: "Kayıt öneki" },
  enrollCol: { en: "Enrollment no", tr: "Kayıt no" },
  treatmentDetailsTitle: { en: "Treatment details (Test / Reference)", tr: "Tedavi künyesi (Test / Referans)" },
  treatmentDetailsTag: { en: "label & export", tr: "etiket & dışa aktarım" },
  mappingHint: {
    en: "Optional. Used in exports and labels. EMA requires reference product identification.",
    tr: "Opsiyonel. Dışa aktarımlarda ve etiketlerde kullanılır. EMA referans ürün künyesini şart koşar.",
  },
  tmCode: { en: "Code", tr: "Kod" },
  tmProduct: { en: "Product", tr: "Ürün" },
  tmSubstance: { en: "Active substance", tr: "Etken madde" },
  tmStrength: { en: "Strength", tr: "Doz / strength" },
  tmFormulation: { en: "Role", tr: "Rol" },
  tmTest: { en: "Test", tr: "Test" },
  tmReference: { en: "Reference", tr: "Referans" },
  tmNone: { en: "—", tr: "—" },
  tmBatch: { en: "Batch / Lot", tr: "Batch / Lot" },
  listType: { en: "List type", tr: "Liste tipi" },
  unblinded: { en: "Unblinded", tr: "Körlemesiz" },
  blinded: { en: "Blinded", tr: "Körlü" },
  blindedHint: {
    en: "Sequences are hidden behind group codes (G1, G2…) so a bioanalyst stays blinded.",
    tr: "Sekanslar grup kodlarının (G1, G2…) ardına gizlenir; biyoanalist kör kalır.",
  },
  groupCode: { en: "Group", tr: "Grup" },
  exportCsv: { en: "Export CSV", tr: "CSV indir" },
  exportXlsx: { en: "Export XLSX", tr: "XLSX indir" },
  balanceTitle: { en: "Balance summary", tr: "Denge özeti" },
  balanceTag: { en: "verify", tr: "doğrula" },
  // Finalize-time balance review
  balanceReviewTitle: { en: "Balance review", tr: "Denge incelemesi" },
  balanceReviewTag: { en: "before finalizing", tr: "sonlandırmadan önce" },
  reviewIntro: {
    en: "Review the allocation below before exporting. Exports are blocked until any imbalance is acknowledged.",
    tr: "Dışa aktarmadan önce aşağıdaki dağılımı inceleyin. Herhangi bir dengesizlik onaylanana kadar dışa aktarım engellenir.",
  },
  balancedAll: { en: "Balanced across all strata", tr: "Tüm tabakalarda dengeli" },
  imbalanceDetected: { en: "Imbalance detected", tr: "Dengesizlik saptandı" },
  byAxis: { en: "Per-axis marginals", tr: "Eksen bazında dağılım" },
  bTarget: { en: "target", tr: "hedef" },
  ackImbalanceLabel: { en: "I acknowledge the imbalance above and want to finalize anyway.", tr: "Yukarıdaki dengesizliği onaylıyorum ve yine de sonlandırmak istiyorum." },
  exportGateMsg: {
    en: "Acknowledge the imbalance below before exporting.",
    tr: "Dışa aktarmadan önce aşağıdaki dengesizliği onaylayın.",
  },
  exportTitle: { en: "Export", tr: "Dışa aktar" },
  bSequence: { en: "Sequence", tr: "Sekans" },
  bGroup: { en: "Group", tr: "Grup" },
  bN: { en: "n", tr: "n" },
  bPerPeriod: { en: "Per-period treatment distribution", tr: "Dönem başına tedavi dağılımı" },
  bReserve: { en: "Reserve", tr: "Yedek" },
  schedule: { en: "Schedule", tr: "Liste" },
  treatmentMapSheet: { en: "Treatment map", tr: "Tedavi künyesi" },
  auditSheet: { en: "Audit", tr: "Denetim" },
  // Faz 3 — stratification
  stratification: { en: "Stratification (optional)", tr: "Tabakalandırma (opsiyonel)" },
  stratificationHint: {
    en: "Single-axis: name:n, comma-separated — e.g. Male:12, Female:12. Multi-axis (factorial): separate factors with | and give a per-cell count — e.g. Site: A, B, C | Sex: M, F | n: 8 makes 6 strata of 8. Each stratum is randomized independently and balanced on its own. Overrides total volunteers.",
    tr: "Tek eksen: ad:n, virgülle — örn. Erkek:12, Kadın:12. Çok eksen (faktöriyel): faktörleri | ile ayırın ve hücre başına sayı verin — örn. Site: A, B, C | Sex: M, F | n: 8 → 8'lik 6 tabaka. Her tabaka bağımsız randomize edilip kendi içinde dengelenir. Toplam gönüllüyü geçersiz kılar.",
  },
  stratumCol: { en: "Stratum", tr: "Tabaka" },
  mStratification: { en: "Stratification", tr: "Tabakalandırma" },
  // Faz 3 — methodology & validation
  methTitle: { en: "Methodology & validation", tr: "Metodoloji & doğrulama" },
  methTag: { en: "reference", tr: "referans" },
  methAlgoH: { en: "Algorithm", tr: "Algoritma" },
  methAlgoP: {
    en: "Allocation uses a seeded, platform-independent mulberry32 pseudo-random number generator (RNG_VERSION 1.0) driving a Fisher–Yates shuffle. The same seed and parameters produce a bit-for-bit identical schedule on any device or browser — no Math.random(), no server, no network. The seed is recorded with every schedule.",
    tr: "Tahsis; Fisher–Yates karıştırmasını süren, seed'li ve platformdan bağımsız bir mulberry32 sözde-rastgele üreteci (RNG_VERSION 1.0) kullanır. Aynı seed ve parametreler her cihaz/tarayıcıda bit-bit aynı listeyi üretir — Math.random() yok, sunucu yok, ağ yok. Seed her listeyle birlikte kaydedilir.",
  },
  methBalanceH: { en: "Balance", tr: "Denge" },
  methBalanceP: {
    en: "Subjects are assigned in permuted blocks so each sequence (crossover) or arm (parallel) receives an equal share within every block. Williams designs are variance-balanced: each treatment appears once per period and each ordered pair of treatments is adjacent equally often, neutralising first-order carryover. Replicate designs (partial TRR/RTR/RRT, full TRTR/RTRT) follow their canonical templates for HVD / reference-scaled analyses.",
    tr: "Denekler permüte bloklar hâlinde atanır; her blok içinde her sekans (çapraz) veya kol (paralel) eşit pay alır. Williams tasarımları varyans-dengelidir: her tedavi dönem başına bir kez görünür ve her sıralı tedavi çifti eşit sıklıkta komşu olur; birinci derece carryover nötralize edilir. Replicate tasarımlar (partial TRR/RTR/RRT, full TRTR/RTRT) HVD / referans-ölçekli analizler için kanonik şablonlarını izler.",
  },
  methKatH: { en: "Known-answer tests", tr: "Bilinen-cevap testleri" },
  methKatP: {
    en: "A committed test suite pins the RNG output and full schedules to fixed expected values (e.g. seed 12345 on a 2×2×2 design yields a known verification code), so any unintended change to the algorithm is caught before release.",
    tr: "Depoya işlenmiş bir test paketi, RNG çıktısını ve tam listeleri sabit beklenen değerlere bağlar (örn. 2×2×2 tasarımda seed 12345 bilinen bir doğrulama kodu verir); böylece algoritmadaki istenmeyen değişiklikler sürümden önce yakalanır.",
  },
  methReproH: { en: "Verification & reproduction", tr: "Doğrulama & yeniden üretim" },
  methReproP: {
    en: "Each schedule is serialised to a canonical string and hashed with SHA-256 (Web Crypto). The first 16 hex characters are shown as a verification code on screen, in the PDF, and in every export filename. An independent auditor can re-enter the seed and parameters, regenerate the list, and confirm the identical hash — making the schedule tamper-evident.",
    tr: "Her liste kanonik bir stringe dönüştürülüp SHA-256 (Web Crypto) ile özetlenir. İlk 16 hex karakter; ekranda, PDF'te ve her dışa aktarım dosya adında doğrulama kodu olarak gösterilir. Bağımsız bir denetçi seed ve parametreleri yeniden girip listeyi üretebilir ve aynı hash'i doğrulayabilir — liste manipülasyona karşı kanıtlanır.",
  },
  methVersionH: { en: "Version", tr: "Sürüm" },
  methVersionP: {
    en: "Tool v1.0.0 · RNG mulberry32 v1.0. Algorithm and version are stamped on every schedule and export.",
    tr: "Araç v1.0.0 · RNG mulberry32 v1.0. Algoritma ve sürüm her liste ve dışa aktarıma damgalanır.",
  },
  // BE blinding & audit delivery
  outputMode: { en: "Output mode", tr: "Çıktı modu" },
  omBlinded: { en: "Blinded (codes)", tr: "Körlü (kodlar)" },
  omUnblinded: { en: "Unblinded (Test/Ref)", tr: "Körlemesiz (Test/Ref)" },
  omBoth: { en: "Both + decode", tr: "İkisi + decode" },
  omBlindedHint: {
    en: "Schedule shows neutral treatment codes only; the Test/Reference identity stays sealed in a separate decode sheet.",
    tr: "Liste yalnız nötr tedavi kodlarını gösterir; Test/Referans kimliği ayrı bir decode belgesinde mühürlü kalır.",
  },
  omUnblindedHint: {
    en: "Test/Reference identity is revealed. Set each code's role in Treatment details below.",
    tr: "Test/Referans kimliği açığa çıkar. Her kodun rolünü aşağıdaki Tedavi künyesinde ayarlayın.",
  },
  omBothHint: {
    en: "Produces the blinded schedule plus a separate sealed decode sheet — both carry the same seed and verification code.",
    tr: "Körlü liste artı ayrı bir mühürlü decode belgesi üretir — ikisi de aynı seed ve doğrulama kodunu taşır.",
  },
  decodeTitle: { en: "Sealed treatment decode", tr: "Mühürlü tedavi decode" },
  decodeTag: { en: "keep sealed", tr: "mühürlü tutun" },
  decodeIntro: {
    en: "Keep this sheet sealed until the analysis is complete. Once unsealed, no data may be changed or excluded.",
    tr: "Bu belgeyi analiz bitene kadar mühürlü tutun. Mühür açıldıktan sonra hiçbir veri değiştirilemez veya dışlanamaz.",
  },
  decodeSetRoles: {
    en: "Set Test/Reference roles in Treatment details to populate the decode sheet.",
    tr: "Decode belgesini doldurmak için Tedavi künyesinde Test/Referans rollerini ayarlayın.",
  },
  sponsor: { en: "Sponsor / CRO", tr: "Sponsor / CRO" },
  protocolVersion: { en: "Protocol version", tr: "Protokol sürümü" },
  protocolDate: { en: "Protocol date", tr: "Protokol tarihi" },
  mSponsor: { en: "Sponsor / CRO", tr: "Sponsor / CRO" },
  mProtocol: { en: "Protocol version / date", tr: "Protokol sürümü / tarihi" },
  decodeSheet: { en: "Decode sheet", tr: "Decode belgesi" },
  validBlocksPrefix: { en: "Use", tr: "Kullan:" },
  // Form group titles
  grpDesign: { en: "Design", tr: "Tasarım" },
  grpCore: { en: "Core randomization", tr: "Çekirdek randomizasyon" },
  grpAudit: { en: "Audit metadata", tr: "Denetim bilgileri" },
  grpNumbering: { en: "Numbering & blinding", tr: "Numaralandırma & körleme" },
  optionalTag: { en: "optional", tr: "opsiyonel" },
  decodeMissingRoles: {
    en: "Both + Decode is selected but no Test/Reference roles are set — the decode sheet will be empty.",
    tr: "Both + Decode seçili ancak Test/Referans rolü girilmemiş — decode belgesi boş kalır.",
  },
  openTreatmentDetails: { en: "Open Treatment details", tr: "Tedavi künyesini aç" },
  decodePreview: { en: "Sealed decode sheet (preview)", tr: "Mühürlü decode belgesi (önizleme)" },
  sealPdfOnly: { en: "Seal / signature fields appear in the PDF only.", tr: "Mühür / imza alanları yalnız PDF'te bulunur." },
  // Operator identity (audit trail) + integrity statement
  generatedBy: { en: "Generated by", tr: "Üreten" },
  generatedByPh: { en: "e.g. James Lind, Study Coordinator", tr: "örn. James Lind, Çalışma Koordinatörü" },
  checkedByField: { en: "Checked by", tr: "Kontrol eden" },
  checkedByPh: { en: "e.g. Aziz Sancar, Biostatistician", tr: "örn. Aziz Sancar, Biyoistatistikçi" },
  mGeneratedBy: { en: "Generated by", tr: "Üreten" },
  mCheckedBy: { en: "Checked by", tr: "Kontrol eden" },
  generatedByHint: {
    en: "Recorded in the audit header and included in the verification code — changing the name changes the code.",
    tr: "Denetim başlığına yazılır ve doğrulama koduna dahil edilir — isim değişirse kod değişir.",
  },
  integrityTitle: { en: "Integrity statement", tr: "Bütünlük beyanı" },
  integrityStatement: {
    en: "This schedule is fully seed-derived. No manual overrides were applied. Any change requires regeneration with a new seed/version, which produces a different verification code.",
    tr: "Bu çizelge tamamen seed'den türetilmiştir. Elle hiçbir değişiklik uygulanmamıştır. Herhangi bir değişiklik yeni bir seed/sürümle yeniden üretim gerektirir ve farklı bir doğrulama kodu üretir.",
  },
  // Run history (client-side versioning)
  historyTitle: { en: "Run history", tr: "Üretim geçmişi" },
  historyTag: { en: "this device only", tr: "yalnız bu cihaz" },
  historyPrivacy: {
    en: "Every generation is saved locally in your browser (localStorage) — timestamp, parameters, and verification code. It never leaves this device. Restoring is read-only; a saved run can't be edited — regenerate for a new version.",
    tr: "Her üretim tarayıcınızda yerel olarak saklanır (localStorage) — zaman damgası, parametreler ve doğrulama kodu. Bu cihazdan çıkmaz. Geri yükleme salt-okunurdur; kayıtlı bir üretim düzenlenemez — yeni sürüm için yeniden üretin.",
  },
  histWhen: { en: "Generated", tr: "Üretim" },
  histStudy: { en: "Study", tr: "Çalışma" },
  histSummary: { en: "Parameters", tr: "Parametreler" },
  histFinal: { en: "Final", tr: "Nihai" },
  histMarkFinal: { en: "Mark as final delivery", tr: "Nihai teslimat olarak işaretle" },
  histRestore: { en: "Restore", tr: "Geri yükle" },
  histDelete: { en: "Delete", tr: "Sil" },
  histClear: { en: "Clear history", tr: "Geçmişi temizle" },
  histClearConfirm: { en: "Clear all saved runs on this device?", tr: "Bu cihazdaki tüm kayıtlı üretimler silinsin mi?" },
  // Faz 3 — PDF signatures
  sigPrepared: { en: "Prepared by", tr: "Hazırlayan" },
  sigChecked: { en: "Checked by", tr: "Kontrol eden" },
  sigApproved: { en: "Approved by", tr: "Onaylayan" },
  sigDate: { en: "Date", tr: "Tarih" },
  sigSignature: { en: "Signature", tr: "İmza" },
  // Verification spec token + independent /verify page
  specTitle: { en: "Verification spec code", tr: "Doğrulama spec kodu" },
  specHint: {
    en: "Keep this spec code with your schedule. Anyone can independently re-verify this exact list at any time — no account needed — on the Verify page, using the code below.",
    tr: "Bu spec kodunu listenizle birlikte saklayın. Herkes, hesap gerekmeden, bu listeyi Doğrulama ekranında dilediği zaman bağımsızca yeniden doğrulayabilir — aşağıdaki kodu kullanarak.",
  },
  specCopy: { en: "Copy spec code", tr: "Spec kodunu kopyala" },
  specCopied: { en: "Copied", tr: "Kopyalandı" },
  specOpenVerify: { en: "Open Verify page", tr: "Doğrulama ekranını aç" },
  verifyNav: { en: "Verify", tr: "Doğrula" },
  verifyHeading: { en: "Verify a schedule", tr: "Bir listeyi doğrula" },
  verifyIntro: {
    en: "Paste a verification spec code to independently reproduce its randomization schedule and confirm it was not altered. This page runs entirely in your browser — nothing is uploaded, nothing is stored. A matching SHA-256 verification code proves the schedule is authentic.",
    tr: "Bir randomizasyon listesini bağımsızca yeniden üretmek ve değiştirilmediğini doğrulamak için doğrulama spec kodunu yapıştırın. Bu ekran tamamen tarayıcınızda çalışır — hiçbir şey yüklenmez, hiçbir şey saklanmaz. Eşleşen bir SHA-256 doğrulama kodu, listenin özgün olduğunu kanıtlar.",
  },
  verifyInputLabel: { en: "Paste your verification spec code", tr: "Doğrulama spec kodunuzu yapıştırın" },
  verifyInputPh: { en: "TG1.…", tr: "TG1.…" },
  verifyCodeLabel: { en: "Verification code from your document (optional)", tr: "Belgenizdeki doğrulama kodu (opsiyonel)" },
  verifyCodePh: { en: "e.g. 4EB8BD233A40E411", tr: "örn. 4EB8BD233A40E411" },
  verifyBtn: { en: "Verify schedule", tr: "Listeyi doğrula" },
  verifyOk: { en: "Verified — this schedule is authentic and fully reproducible.", tr: "Doğrulandı — bu liste özgün ve tamamen yeniden üretilebilir." },
  verifyFail: { en: "Does not match — this schedule could not be reproduced from the code provided.", tr: "Eşleşmiyor — bu liste, verilen koddan yeniden üretilemedi." },
  verifyRecomputed: { en: "Recomputed verification code", tr: "Yeniden hesaplanan doğrulama kodu" },
  verifyExpected: { en: "Code carried in the spec", tr: "Spec içindeki kod" },
  verifyDocCode: { en: "Code you entered", tr: "Girdiğiniz kod" },
  verifyMatch: { en: "match", tr: "eşleşiyor" },
  verifyNoMatch: { en: "no match", tr: "eşleşmiyor" },
  verifyErrToken: {
    en: "This spec code looks incomplete or altered. Please copy it again, in full, from the source document.",
    tr: "Bu spec kodu eksik veya değiştirilmiş görünüyor. Lütfen kaynak belgeden eksiksiz olarak yeniden kopyalayın.",
  },
  verifyErrRepro: {
    en: "The parameters in this spec code did not produce a valid schedule.",
    tr: "Bu spec kodundaki parametreler geçerli bir liste üretmedi.",
  },
  verifyVersionNotice: {
    en: "This schedule was generated with a different engine version than the one you are verifying on. The result below is reproduced using the engine version recorded in the spec.",
    tr: "Bu liste, doğrulama yaptığınız sürümden farklı bir motor sürümüyle üretilmiş. Aşağıdaki sonuç, spec içinde kayıtlı motor sürümü kullanılarak yeniden üretilmiştir.",
  },
  verifyReadonly: { en: "This page reproduces and compares only — it changes nothing.", tr: "Bu ekran yalnız yeniden üretir ve karşılaştırır — hiçbir şeyi değiştirmez." },
  verifyReproHeading: { en: "Reproduced schedule", tr: "Yeniden üretilen liste" },
  verifyOpenTool: { en: "Open the randomization tool", tr: "Randomizasyon aracını aç" },
  verifyEnginePaper: { en: "Verified engine", tr: "Doğrulanan motor" },
  verifyHeroLink: { en: "Already have a schedule? Verify it →", tr: "Zaten bir listeniz mi var? Doğrulayın →" },
  verifyTokenHint: {
    en: "Required — the long code that begins with TG1. Use “Copy spec code” in the tool, or the spec line in your export/PDF.",
    tr: "Zorunlu — TG1 ile başlayan uzun kod. Araçtaki “Copy spec code” butonunu ya da çıktı/PDF'teki spec satırını kullanın.",
  },
  verifyCodeHint: {
    en: "Optional cross-check only. The short verification code cannot reproduce a schedule on its own — what gets verified is the TG1 spec code above.",
    tr: "Yalnız ek kontrol. Kısa doğrulama kodu tek başına bir listeyi yeniden üretemez — doğrulanan şey yukarıdaki TG1 spec kodudur.",
  },
  verifyNeedToken: {
    en: "Enter the full spec code (it starts with TG1) in the box above — the short verification code on its own cannot reproduce the schedule. Get it from “Copy spec code” in the tool, or the spec line in your export/PDF.",
    tr: "Üstteki kutuya tam spec kodunu (TG1 ile başlar) girin — kısa doğrulama kodu tek başına listeyi yeniden üretemez. Kodu araçtaki “Copy spec code” butonundan ya da çıktı/PDF'teki spec satırından alın.",
  },
};

export function tr(lang: Lang, key: keyof typeof D): string {
  return D[key][lang];
}
