// Bilingual UI strings for the randomization tool.
export type Lang = "en" | "tr";

type Dict = Record<string, { en: string; tr: string }>;

const D: Dict = {
  eyebrow: {
    en: "Randomization for bioequivalence & crossover trials",
    tr: "Biyoeşdeğerlik & çapraz çalışmalar için randomizasyon",
  },
  heading: { en: "Randomization.", tr: "Randomizasyon." },
  lede: {
    en: "Generate verifiable, reproducible randomization schedules for bioequivalence, bioavailability, and crossover trials — including replicate designs for highly variable drugs. Every schedule carries a seed, algorithm version, and SHA-256 verification code so an independent auditor can reproduce it. Runs entirely in your browser; your data never leaves this device.",
    tr: "Biyoeşdeğerlik, biyoyararlanım ve çapraz çalışmalar için — yüksek değişkenlikli ilaçlara yönelik replicate tasarımlar dâhil — doğrulanabilir, yeniden üretilebilir randomizasyon listeleri üretin. Her liste; seed, algoritma sürümü ve SHA-256 doğrulama kodu taşır; böylece bağımsız bir denetçi listeyi yeniden üretebilir. Tamamen tarayıcınızda çalışır; veriniz bu cihazdan çıkmaz.",
  },
  studyParams: { en: "Study parameters", tr: "Çalışma parametreleri" },
  configure: { en: "configure", tr: "yapılandır" },
  method: { en: "Method", tr: "Yöntem" },
  parallel: { en: "Parallel", tr: "Paralel" },
  crossover: { en: "Crossover", tr: "Çapraz" },
  design: { en: "Crossover design", tr: "Çapraz tasarım" },
  selectDesign: { en: "Select a design", tr: "Bir tasarım seçin" },
  totalVolunteers: { en: "Total volunteers", tr: "Toplam gönüllü" },
  drugs: { en: "Drugs", tr: "İlaçlar" },
  drugsHintReplicate: {
    en: "First = Test (T), second = Reference (R).",
    tr: "İlki = Test (T), ikincisi = Referans (R).",
  },
  periodsDerived: { en: "Periods", tr: "Dönem" },
  seqCount: { en: "Sequences", tr: "Sekans" },
  seed: { en: "Seed", tr: "Seed" },
  randomize: { en: "randomize", tr: "rastgele" },
  blockSize: { en: "Block size", tr: "Blok boyutu" },
  pleaseSelect: { en: "Please select", tr: "Lütfen seçin" },
  allocationRatio: { en: "Allocation ratio", tr: "Tahsis oranı" },
  studyCode: { en: "Study / protocol code (optional)", tr: "Çalışma / protokol kodu (opsiyonel)" },
  generate: { en: "Generate", tr: "Üret" },
  exportPdf: { en: "Export PDF", tr: "PDF indir" },
  selectMethodFirst: { en: "Generate a schedule first.", tr: "Önce bir liste üretin." },
  suggestionPrefix: { en: "Try", tr: "Deneyin:" },
  // result + audit
  idCol: { en: "ID", tr: "ID" },
  seqCol: { en: "Sequence", tr: "Sekans" },
  period: { en: "Period", tr: "Dönem" },
  treatment: { en: "Treatment", tr: "Tedavi" },
  auditTitle: { en: "Audit & reproducibility", tr: "Denetim & yeniden üretim" },
  verified: { en: "verifiable", tr: "doğrulanabilir" },
  mDesign: { en: "Design", tr: "Tasarım" },
  mTreatments: { en: "Treatments", tr: "Tedavi sayısı" },
  mSequences: { en: "Sequences", tr: "Sekans sayısı" },
  mPerSeq: { en: "Subjects / sequence", tr: "Denek / sekans" },
  mSeed: { en: "Seed", tr: "Seed" },
  mAlgo: { en: "Algorithm", tr: "Algoritma" },
  mBlock: { en: "Block size", tr: "Blok boyutu" },
  mGenerated: { en: "Generated", tr: "Üretim zamanı" },
  mTool: { en: "Tool", tr: "Araç" },
  mVerification: { en: "Verification code", tr: "Doğrulama kodu" },
  varianceBalanced: { en: "variance-balanced", tr: "varyans-dengeli" },
  reproCheck: { en: "Reproducibility check", tr: "Yeniden üretim kontrolü" },
  reproOk: { en: "Reproduced — identical (hash match)", tr: "Yeniden üretildi — birebir aynı (hash eşleşti)" },
  reproMismatch: { en: "Mismatch — hash differs", tr: "Uyuşmuyor — hash farklı" },
  reproHint: {
    en: "Re-runs the same seed + parameters and compares the SHA-256 hash.",
    tr: "Aynı seed + parametrelerle yeniden üretip SHA-256 hash'i karşılaştırır.",
  },
  // Faz 2 — field workflow
  reserveSubjects: { en: "Reserve subjects", tr: "Yedek denekler" },
  reserveTag: { en: "Reserve", tr: "Yedek" },
  optionsTitle: { en: "Numbering & reserves", tr: "Numaralandırma & yedekler" },
  options: { en: "options", tr: "seçenekler" },
  randPrefix: { en: "Rand. no prefix", tr: "Rand. no öneki" },
  startNo: { en: "Start", tr: "Başlangıç" },
  padWidth: { en: "Digits", tr: "Basamak" },
  enrollEnabled: { en: "Separate enrollment number", tr: "Ayrı kayıt numarası" },
  enrollPrefix: { en: "Enroll. prefix", tr: "Kayıt öneki" },
  enrollCol: { en: "Enrollment no", tr: "Kayıt no" },
  treatmentDetailsTitle: { en: "Treatment details (Test / Reference)", tr: "Tedavi künyesi (Test / Referans)" },
  treatmentDetailsTag: { en: "label & export", tr: "etiket & dışa aktarım" },
  mappingHint: {
    en: "Optional. Used in exports and labels. EMA requires reference product identification.",
    tr: "Opsiyonel. Dışa aktarımlarda ve etiketlerde kullanılır. EMA referans ürün künyesini şart koşar.",
  },
  tmCode: { en: "Code", tr: "Kod" },
  tmProduct: { en: "Product", tr: "Ürün" },
  tmSubstance: { en: "Active substance", tr: "Etken madde" },
  tmStrength: { en: "Strength", tr: "Doz / strength" },
  tmFormulation: { en: "Role", tr: "Rol" },
  tmTest: { en: "Test", tr: "Test" },
  tmReference: { en: "Reference", tr: "Referans" },
  tmNone: { en: "—", tr: "—" },
  tmBatch: { en: "Batch / Lot", tr: "Batch / Lot" },
  listType: { en: "List type", tr: "Liste tipi" },
  unblinded: { en: "Unblinded", tr: "Körlemesiz" },
  blinded: { en: "Blinded", tr: "Körlü" },
  blindedHint: {
    en: "Sequences are hidden behind group codes (G1, G2…) so a bioanalyst stays blinded.",
    tr: "Sekanslar grup kodlarının (G1, G2…) ardına gizlenir; biyoanalist kör kalır.",
  },
  groupCode: { en: "Group", tr: "Grup" },
  exportCsv: { en: "Export CSV", tr: "CSV indir" },
  exportXlsx: { en: "Export XLSX", tr: "XLSX indir" },
  balanceTitle: { en: "Balance summary", tr: "Denge özeti" },
  balanceTag: { en: "verify", tr: "doğrula" },
  bSequence: { en: "Sequence", tr: "Sekans" },
  bGroup: { en: "Group", tr: "Grup" },
  bN: { en: "n", tr: "n" },
  bPerPeriod: { en: "Per-period treatment distribution", tr: "Dönem başına tedavi dağılımı" },
  bReserve: { en: "Reserve", tr: "Yedek" },
  schedule: { en: "Schedule", tr: "Liste" },
  treatmentMapSheet: { en: "Treatment map", tr: "Tedavi künyesi" },
  auditSheet: { en: "Audit", tr: "Denetim" },
  // Faz 3 — stratification
  stratification: { en: "Stratification (optional)", tr: "Tabakalandırma (opsiyonel)" },
  stratificationHint: {
    en: "Format: name:n, comma-separated — e.g. Male:12, Female:12. Each stratum is randomized independently and balanced on its own. Overrides total volunteers.",
    tr: "Biçim: ad:n, virgülle — örn. Erkek:12, Kadın:12. Her tabaka bağımsız randomize edilip kendi içinde dengelenir. Toplam gönüllüyü geçersiz kılar.",
  },
  stratumCol: { en: "Stratum", tr: "Tabaka" },
  mStratification: { en: "Stratification", tr: "Tabakalandırma" },
  // Faz 3 — methodology & validation
  methTitle: { en: "Methodology & validation", tr: "Metodoloji & doğrulama" },
  methTag: { en: "reference", tr: "referans" },
  methAlgoH: { en: "Algorithm", tr: "Algoritma" },
  methAlgoP: {
    en: "Allocation uses a seeded, platform-independent mulberry32 pseudo-random number generator (RNG_VERSION 1.0) driving a Fisher–Yates shuffle. The same seed and parameters produce a bit-for-bit identical schedule on any device or browser — no Math.random(), no server, no network. The seed is recorded with every schedule.",
    tr: "Tahsis; Fisher–Yates karıştırmasını süren, seed'li ve platformdan bağımsız bir mulberry32 sözde-rastgele üreteci (RNG_VERSION 1.0) kullanır. Aynı seed ve parametreler her cihaz/tarayıcıda bit-bit aynı listeyi üretir — Math.random() yok, sunucu yok, ağ yok. Seed her listeyle birlikte kaydedilir.",
  },
  methBalanceH: { en: "Balance", tr: "Denge" },
  methBalanceP: {
    en: "Subjects are assigned in permuted blocks so each sequence (crossover) or arm (parallel) receives an equal share within every block. Williams designs are variance-balanced: each treatment appears once per period and each ordered pair of treatments is adjacent equally often, neutralising first-order carryover. Replicate designs (partial TRR/RTR/RRT, full TRTR/RTRT) follow their canonical templates for HVD / reference-scaled analyses.",
    tr: "Denekler permüte bloklar hâlinde atanır; her blok içinde her sekans (çapraz) veya kol (paralel) eşit pay alır. Williams tasarımları varyans-dengelidir: her tedavi dönem başına bir kez görünür ve her sıralı tedavi çifti eşit sıklıkta komşu olur; birinci derece carryover nötralize edilir. Replicate tasarımlar (partial TRR/RTR/RRT, full TRTR/RTRT) HVD / referans-ölçekli analizler için kanonik şablonlarını izler.",
  },
  methKatH: { en: "Known-answer tests", tr: "Bilinen-cevap testleri" },
  methKatP: {
    en: "A committed test suite pins the RNG output and full schedules to fixed expected values (e.g. seed 12345 on a 2×2×2 design yields a known verification code), so any unintended change to the algorithm is caught before release.",
    tr: "Depoya işlenmiş bir test paketi, RNG çıktısını ve tam listeleri sabit beklenen değerlere bağlar (örn. 2×2×2 tasarımda seed 12345 bilinen bir doğrulama kodu verir); böylece algoritmadaki istenmeyen değişiklikler sürümden önce yakalanır.",
  },
  methReproH: { en: "Verification & reproduction", tr: "Doğrulama & yeniden üretim" },
  methReproP: {
    en: "Each schedule is serialised to a canonical string and hashed with SHA-256 (Web Crypto). The first 16 hex characters are shown as a verification code on screen, in the PDF, and in every export filename. An independent auditor can re-enter the seed and parameters, regenerate the list, and confirm the identical hash — making the schedule tamper-evident.",
    tr: "Her liste kanonik bir stringe dönüştürülüp SHA-256 (Web Crypto) ile özetlenir. İlk 16 hex karakter; ekranda, PDF'te ve her dışa aktarım dosya adında doğrulama kodu olarak gösterilir. Bağımsız bir denetçi seed ve parametreleri yeniden girip listeyi üretebilir ve aynı hash'i doğrulayabilir — liste manipülasyona karşı kanıtlanır.",
  },
  methVersionH: { en: "Version", tr: "Sürüm" },
  methVersionP: {
    en: "Tool v1.0.0 · RNG mulberry32 v1.0. Algorithm and version are stamped on every schedule and export.",
    tr: "Araç v1.0.0 · RNG mulberry32 v1.0. Algoritma ve sürüm her liste ve dışa aktarıma damgalanır.",
  },
  // BE blinding & audit delivery
  outputMode: { en: "Output mode", tr: "Çıktı modu" },
  omBlinded: { en: "Blinded (codes)", tr: "Körlü (kodlar)" },
  omUnblinded: { en: "Unblinded (Test/Ref)", tr: "Körlemesiz (Test/Ref)" },
  omBoth: { en: "Both + decode", tr: "İkisi + decode" },
  omBlindedHint: {
    en: "Schedule shows neutral treatment codes only; the Test/Reference identity stays sealed in a separate decode sheet.",
    tr: "Liste yalnız nötr tedavi kodlarını gösterir; Test/Referans kimliği ayrı bir decode belgesinde mühürlü kalır.",
  },
  omUnblindedHint: {
    en: "Test/Reference identity is revealed. Set each code's role in Treatment details below.",
    tr: "Test/Referans kimliği açığa çıkar. Her kodun rolünü aşağıdaki Tedavi künyesinde ayarlayın.",
  },
  omBothHint: {
    en: "Produces the blinded schedule plus a separate sealed decode sheet — both carry the same seed and verification code.",
    tr: "Körlü liste artı ayrı bir mühürlü decode belgesi üretir — ikisi de aynı seed ve doğrulama kodunu taşır.",
  },
  decodeTitle: { en: "Sealed treatment decode", tr: "Mühürlü tedavi decode" },
  decodeTag: { en: "keep sealed", tr: "mühürlü tutun" },
  decodeIntro: {
    en: "Keep this sheet sealed until the analysis is complete. Once unsealed, no data may be changed or excluded.",
    tr: "Bu belgeyi analiz bitene kadar mühürlü tutun. Mühür açıldıktan sonra hiçbir veri değiştirilemez veya dışlanamaz.",
  },
  decodeSetRoles: {
    en: "Set Test/Reference roles in Treatment details to populate the decode sheet.",
    tr: "Decode belgesini doldurmak için Tedavi künyesinde Test/Referans rollerini ayarlayın.",
  },
  sponsor: { en: "Sponsor / CRO", tr: "Sponsor / CRO" },
  protocolVersion: { en: "Protocol version", tr: "Protokol sürümü" },
  protocolDate: { en: "Protocol date", tr: "Protokol tarihi" },
  mSponsor: { en: "Sponsor / CRO", tr: "Sponsor / CRO" },
  mProtocol: { en: "Protocol version / date", tr: "Protokol sürümü / tarihi" },
  decodeSheet: { en: "Decode sheet", tr: "Decode belgesi" },
  validBlocksPrefix: { en: "Use", tr: "Kullan:" },
  // Form group titles
  grpDesign: { en: "Design", tr: "Tasarım" },
  grpCore: { en: "Core randomization", tr: "Çekirdek randomizasyon" },
  grpAudit: { en: "Audit metadata", tr: "Denetim bilgileri" },
  grpNumbering: { en: "Numbering & blinding", tr: "Numaralandırma & körleme" },
  optionalTag: { en: "optional", tr: "opsiyonel" },
  decodeMissingRoles: {
    en: "Both + Decode is selected but no Test/Reference roles are set — the decode sheet will be empty.",
    tr: "Both + Decode seçili ancak Test/Referans rolü girilmemiş — decode belgesi boş kalır.",
  },
  openTreatmentDetails: { en: "Open Treatment details", tr: "Tedavi künyesini aç" },
  decodePreview: { en: "Sealed decode sheet (preview)", tr: "Mühürlü decode belgesi (önizleme)" },
  sealPdfOnly: { en: "Seal / signature fields appear in the PDF only.", tr: "Mühür / imza alanları yalnız PDF'te bulunur." },
  // Faz 3 — PDF signatures
  sigPrepared: { en: "Prepared by", tr: "Hazırlayan" },
  sigChecked: { en: "Checked by", tr: "Kontrol eden" },
  sigApproved: { en: "Approved by", tr: "Onaylayan" },
  sigDate: { en: "Date", tr: "Tarih" },
  sigSignature: { en: "Signature", tr: "İmza" },
};

export function tr(lang: Lang, key: keyof typeof D): string {
  return D[key][lang];
}
